window.__SITE_DATA__ = {
  "news": [
    {
      "date": "2023-06-23",
      "date_zh": "2023.06.23",
      "date_en": "Jun 23, 2023",
      "title_zh": "硕士毕业啦！",
      "title_en": "Graduated with my Master's!",
      "desc_zh": "刘雨辰从东北农业大学发育生物学专业硕士毕业。",
      "desc_en": "Yuchen Liu graduated with a Master's degree in Developmental Biology from Northeast Agricultural University.",
      "image": "assets/xinwen1.JPG",
      "content_zh": "2023年6月23日，刘雨辰从东北农业大学发育生物学专业硕士毕业，获得硕士学位。",
      "content_en": "On June 23, 2023, Yuchen Liu graduated from Northeast Agricultural University with a Master's degree in Developmental Biology.",
      "sort": 9999,
      "file": "01-master-graduated.md",
      "body": ""
    },
    {
      "date": "2023-09-01",
      "date_zh": "2023.09.01",
      "date_en": "Sep 1, 2023",
      "title_zh": "开始攻读博士学位！",
      "title_en": "Started my PhD!",
      "desc_zh": "刘雨辰来到南开大学生物化学与分子生物学专业攻读博士学位。",
      "desc_en": "Yuchen Liu started his PhD in Biochemistry and Molecular Biology at Nankai University.",
      "image": "assets/xinwen2.JPG",
      "content_zh": "2023年9月1日，刘雨辰来到南开大学，进入生物化学与分子生物学专业攻读博士学位。",
      "content_en": "On September 1, 2023, Yuchen Liu joined Nankai University to pursue a PhD in Biochemistry and Molecular Biology.",
      "sort": 9999,
      "file": "02-phd-started.md",
      "body": ""
    },
    {
      "date": "2026-09-09",
      "date_zh": "2026.09.09",
      "date_en": "Sep 9, 2026",
      "title_zh": "终于投稿自己的第一篇文章了！",
      "title_en": "Finally submitted my first paper!",
      "desc_zh": "刘雨辰开始投稿自己的第一篇文章。",
      "desc_en": "Yuchen Liu began submitting his first paper.",
      "image": "assets/xinwen3.PNG",
      "content_zh": "2026年9月9日，刘雨辰开始投稿自己的第一篇学术论文。",
      "content_en": "On September 9, 2026, Yuchen Liu began submitting his first academic paper.",
      "sort": 9999,
      "file": "03-paper-submitted.md",
      "body": ""
    }
  ],
  "people": [
    {
      "category": "alumni",
      "name_zh": "已毕业校友A",
      "name_en": "Alumnus A",
      "image": "assets/biyea.JPG",
      "role_zh": "硕士毕业 (2024)",
      "role_en": "MS (2024)",
      "focus_zh": "去向：博士深造",
      "focus_en": "Now: PhD study",
      "bio_zh": "2024 年硕士毕业，研究方向为转录组数据分析，毕业后前往高校继续攻读博士学位。",
      "bio_en": "Graduated with a Master's degree in 2024, focusing on transcriptome data analysis. Currently pursuing a PhD at a university.",
      "sort": 1,
      "file": "alumni-a.md",
      "body": ""
    },
    {
      "category": "pi",
      "name_zh": "刘雨辰",
      "name_en": "Yuchen Liu",
      "image": "assets/liuyuchen.JPG",
      "role_zh": "博士研究生",
      "role_en": "PhD Candidate",
      "focus_zh": "早期胚胎发育 · 干细胞 · 生殖衰老",
      "focus_en": "Early Embryonic Development · Stem Cells · Reproductive Aging",
      "bioShort_zh": "南开大学博士研究生，主要研究方向为发育生物学，聚焦早期胚胎发育、干细胞多能性调控与生殖衰老。",
      "bioShort_en": "PhD Candidate at Nankai University. Research focuses on developmental biology, early embryonic development, stem cell pluripotency, and reproductive aging.",
      "bio_zh": "刘雨辰现为南开大学博士研究生，主要研究方向为发育生物学，聚焦早期胚胎发育、干细胞多能性调控与生殖衰老等问题。致力于结合单细胞测序、基因编辑与生物信息学方法，解析哺乳动物胚胎发育过程中的细胞命运决定机制，并探索生殖衰老的分子基础与干预策略。",
      "bio_en": "Yuchen Liu is currently a PhD Candidate at Nankai University. His research focuses on developmental biology, with particular interests in early embryonic development, stem cell pluripotency regulation, and reproductive aging. He combines single-cell sequencing, genome editing, and bioinformatics to dissect the molecular mechanisms of cell fate determination during mammalian embryogenesis and to explore the molecular basis and intervention strategies of reproductive aging.",
      "interests_zh": "研究方向：早期胚胎发育 · 干细胞 · 生殖衰老",
      "interests_en": "Research: Early Embryonic Development · Stem Cells · Reproductive Aging",
      "sort": 1,
      "file": "pi-liuyuchen.md",
      "body": ""
    },
    {
      "category": "postdocs",
      "name_zh": "博士后",
      "name_en": "Postdoctoral Fellow",
      "image": "assets/boshihou.JPG",
      "role_zh": "博士后",
      "role_en": "Postdoctoral Fellow",
      "focus_zh": "早期胚胎发育",
      "focus_en": "Early embryonic development",
      "bio_zh": "主要从事哺乳动物早期胚胎发育与细胞命运决定的分子机制研究，利用单细胞测序技术解析胚胎发育过程中的基因调控网络。",
      "bio_en": "Focuses on the molecular mechanisms of early mammalian embryonic development and cell fate determination, using single-cell sequencing to dissect gene regulatory networks during embryogenesis.",
      "sort": 1,
      "file": "postdoc.md",
      "body": ""
    },
    {
      "category": "staff",
      "name_zh": "科研助理",
      "name_en": "Research Assistant",
      "image": "assets/keyanzhuli.JPG",
      "role_zh": "科研助理",
      "role_en": "Research Assistant",
      "focus_zh": "实验室行政管理",
      "focus_en": "Lab administration",
      "bio_zh": "负责课题组日常行政事务、经费管理与仪器设备维护，保障实验室高效运转。",
      "bio_en": "Responsible for daily lab administration, funding management, and equipment maintenance to ensure efficient lab operation.",
      "sort": 1,
      "file": "staff-assistant.md",
      "body": ""
    },
    {
      "category": "students",
      "name_zh": "博士研究生",
      "name_en": "PhD Student",
      "image": "assets/boshiyanjiusheng.JPG",
      "role_zh": "博士在读 (2024 级)",
      "role_en": "PhD Candidate (2024)",
      "focus_zh": "单细胞转录组分析",
      "focus_en": "Single-cell transcriptome",
      "bio_zh": "研究方向为早期胚胎发育过程中的单细胞转录组动态变化，致力于开发高效的单细胞数据分析方法。",
      "bio_en": "Studies single-cell transcriptome dynamics during early embryonic development, aiming to develop efficient single-cell data analysis methods.",
      "sort": 1,
      "file": "student-phd.md",
      "body": ""
    },
    {
      "category": "undergrads",
      "name_zh": "本科同学A",
      "name_en": "Undergrad A",
      "image": "assets/benkeshenga.JPG",
      "role_zh": "本科科研训练",
      "role_en": "Undergrad Research",
      "focus_zh": "qPCR 数据分析",
      "focus_en": "qPCR analysis",
      "bio_zh": "参与 qPCR 相对表达量分析方法的研究，协助开发相关 R 包。",
      "bio_en": "Participates in qPCR relative expression analysis research, assisting in the development of related R packages.",
      "sort": 1,
      "file": "undergrad-a.md",
      "body": ""
    },
    {
      "category": "alumni",
      "name_zh": "已毕业校友B",
      "name_en": "Alumnus B",
      "image": "assets/biyeb.JPG",
      "role_zh": "本科毕业 (2023)",
      "role_en": "BS (2023)",
      "focus_zh": "去向：企业就业",
      "focus_en": "Now: Industry",
      "bio_zh": "2023 年本科毕业，曾参与 R 包开发项目，毕业后进入生物医药企业从事研发工作。",
      "bio_en": "Graduated with a Bachelor's degree in 2023, participated in R package development projects. Currently working in R&D at a biopharmaceutical company.",
      "sort": 2,
      "file": "alumni-b.md",
      "body": ""
    },
    {
      "category": "staff",
      "name_zh": "实验员",
      "name_en": "Lab Technician",
      "image": "assets/shiyanyuan.JPG",
      "role_zh": "实验员",
      "role_en": "Lab Technician",
      "focus_zh": "实验技术支持",
      "focus_en": "Lab technical support",
      "bio_zh": "负责分子生物学与细胞培养相关实验的技术支持，协助课题组成员完成实验操作与数据分析。",
      "bio_en": "Provides technical support for molecular biology and cell culture experiments, assisting lab members with experimental procedures and data analysis.",
      "sort": 2,
      "file": "staff-technician.md",
      "body": ""
    },
    {
      "category": "students",
      "name_zh": "硕士研究A",
      "name_en": "Master A",
      "image": "assets/yanjiushenga.JPG",
      "role_zh": "硕士在读 (2025 级)",
      "role_en": "Master Student (2025)",
      "focus_zh": "转录组标准化方法",
      "focus_en": "Transcriptome normalization",
      "bio_zh": "研究转录组数据标准化算法，关注 ERCC spike-in 在 RNA-Seq 定量中的应用。",
      "bio_en": "Investigates transcriptome normalization algorithms, focusing on ERCC spike-in applications in RNA-Seq quantification.",
      "sort": 2,
      "file": "student-master-a.md",
      "body": ""
    },
    {
      "category": "undergrads",
      "name_zh": "本科同学B",
      "name_en": "Undergrad B",
      "image": "assets/bengkeshengb.JPG",
      "role_zh": "本科科研训练",
      "role_en": "Undergrad Research",
      "focus_zh": "R 包开发辅助",
      "focus_en": "R package dev",
      "bio_zh": "参与课题组生物信息学 R 包的开发与测试，学习软件开发与版本管理。",
      "bio_en": "Participates in the development and testing of the lab's bioinformatics R packages, learning software development and version control.",
      "sort": 2,
      "file": "undergrad-b.md",
      "body": ""
    },
    {
      "category": "students",
      "name_zh": "硕士研究B",
      "name_en": "Master B",
      "image": "assets/yanjiushengb.JPG",
      "role_zh": "硕士在读 (2025 级)",
      "role_en": "Master Student (2025)",
      "focus_zh": "CRISPR 实验设计工具",
      "focus_en": "CRISPR design tools",
      "bio_zh": "开发 CRISPR 基因编辑实验的自动化设计工具，提高 sgRNA 设计效率与准确性。",
      "bio_en": "Develops automated design tools for CRISPR gene editing experiments to improve sgRNA design efficiency and accuracy.",
      "sort": 3,
      "file": "student-master-b.md",
      "body": ""
    },
    {
      "category": "students",
      "name_zh": "硕士研究C",
      "name_en": "Master C",
      "image": "assets/yanjiushengc.JPG",
      "role_zh": "硕士在读 (2026 级)",
      "role_en": "Master Student (2026)",
      "focus_zh": "基因集富集分析",
      "focus_en": "Gene set enrichment",
      "bio_zh": "研究基因集富集分析（GSEA）方法的优化与可视化，开发便捷的 GMT 文件生成工具。",
      "bio_en": "Optimizes gene set enrichment analysis (GSEA) methods and visualization, developing convenient GMT file generation tools.",
      "sort": 4,
      "file": "student-master-c.md",
      "body": ""
    }
  ],
  "publications": [
    {
      "year": "2022",
      "type": "journal",
      "research": "embryonic-development",
      "citation_zh": "<strong>刘雨辰</strong>, 杨芷珊, 张宇霆, 刘忠华, 翁晓刚 (2022). 哺乳动物早期胚胎发育过程中X染色体失活的研究进展. <em>中国细胞生物学学报</em> 44(11): 2223-2232. DOI: 10.11844/cjcb.2022.11.0019",
      "citation_en": "<strong>Liu Y</strong>, Yang Z, Zhang Y, Liu Z, Weng X (2022). Research progress on X chromosome inactivation during early mammalian embryonic development. <em>Chinese Journal of Cell Biology</em> 44(11): 2223-2232. DOI: 10.11844/cjcb.2022.11.0019",
      "link": "https://doi.org/10.11844/cjcb.2022.11.0019",
      "sort": 2,
      "file": "01-x-chromosome-2022.md",
      "body": ""
    },
    {
      "year": "2023",
      "type": "journal",
      "research": "reproductive-aging",
      "citation_zh": "Zhang, Y., W. Yuan, <strong>Y. Liu</strong>, Y. Liu, H. Liang, Q. Xu, Z. Liu and X. Weng (2023). Plasma membrane lipid composition and metabolomics analysis of Yorkshire boar sperms with high and low resistance to cryopreservation. <em>Theriogenology</em> 206: 28-39. DOI: 10.1016/j.theriogenology.2023.04.016",
      "citation_en": "Zhang, Y., W. Yuan, <strong>Y. Liu</strong>, Y. Liu, H. Liang, Q. Xu, Z. Liu and X. Weng (2023). Plasma membrane lipid composition and metabolomics analysis of Yorkshire boar sperms with high and low resistance to cryopreservation. <em>Theriogenology</em> 206: 28-39. DOI: 10.1016/j.theriogenology.2023.04.016",
      "link": "https://doi.org/10.1016/j.theriogenology.2023.04.016",
      "sort": 1,
      "file": "02-theriogenology-2023.md",
      "body": ""
    },
    {
      "year": "2023",
      "type": "software",
      "citation_zh": "<strong>Liu Y.</strong> qqpcr: Quick qPCR relative expression. GitHub open-source R package, 2023.",
      "citation_en": "<strong>Liu Y.</strong> qqpcr: Quick qPCR relative expression. GitHub open-source R package, 2023.",
      "link": "https://github.com/liuyuchenlab/qqpcr",
      "sort": 6,
      "file": "03-qqpcr-2023.md",
      "body": ""
    },
    {
      "year": "2024",
      "type": "software",
      "citation_zh": "<strong>Liu Y.</strong> qqgmt: One-click DIY GMT file generation for GSEA. GitHub open-source R package, 2024.",
      "citation_en": "<strong>Liu Y.</strong> qqgmt: One-click DIY GMT file generation for GSEA. GitHub open-source R package, 2024.",
      "link": "https://github.com/liuyuchenlab/qqgmt",
      "sort": 3,
      "file": "04-qqgmt-2024.md",
      "body": ""
    },
    {
      "year": "2024",
      "type": "software",
      "citation_zh": "<strong>Liu Y.</strong> qqdeg: One-click DEG and enrichment results. GitHub open-source R package, 2024.",
      "citation_en": "<strong>Liu Y.</strong> qqdeg: One-click DEG and enrichment results. GitHub open-source R package, 2024.",
      "link": "https://github.com/liuyuchenlab/qqdeg",
      "sort": 4,
      "file": "05-qqdeg-2024.md",
      "body": ""
    },
    {
      "year": "2024",
      "type": "software",
      "citation_zh": "<strong>Liu Y.</strong> qqseq: One-click exon and intron sequences from transcripts. GitHub open-source R package, 2024.",
      "citation_en": "<strong>Liu Y.</strong> qqseq: One-click exon and intron sequences from transcripts. GitHub open-source R package, 2024.",
      "link": "https://github.com/liuyuchenlab/qqseq",
      "sort": 5,
      "file": "06-qqseq-2024.md",
      "body": ""
    }
  ],
  "research": [
    {
      "sort": 1,
      "title_zh": "早期胚胎发育",
      "title_en": "Early Embryonic Development",
      "desc_zh": "研究哺乳动物早期胚胎发育过程中的细胞命运决定与基因调控网络，解析合子基因组激活、谱系分化与X染色体失活等关键发育事件的分子机制。",
      "desc_en": "Studying cell fate determination and gene regulatory networks in early mammalian embryonic development, dissecting zygotic genome activation, lineage specification, and X chromosome inactivation.",
      "tags_zh": "胚胎,合子基因组激活,谱系分化,X染色体失活",
      "tags_en": "Embryo,ZGA,Lineage,XCI",
      "file": "embryonic-development.md",
      "body": ""
    },
    {
      "sort": 2,
      "title_zh": "胚胎干细胞",
      "title_en": "Embryonic Stem Cells",
      "desc_zh": "探索胚胎干细胞的干性维持与定向分化机制，刻画干细胞状态转换、表观遗传重编程以及向特定谱系分化的调控网络。",
      "desc_en": "Exploring pluripotency maintenance and directed differentiation of embryonic stem cells, characterizing state transitions, epigenetic reprogramming, and lineage-specific regulatory networks.",
      "tags_zh": "胚胎干细胞,多能性,分化,表观遗传",
      "tags_en": "ESC,Pluripotency,Differentiation,Epigenetics",
      "file": "embryonic-stem-cells.md",
      "body": ""
    },
    {
      "sort": 3,
      "title_zh": "再生医学",
      "title_en": "Regenerative Medicine",
      "desc_zh": "利用干细胞与类器官技术研究组织器官再生机制，构建体外类器官模型，开发面向组织损伤修复与功能重建的再生医学策略。",
      "desc_en": "Utilizing stem cell and organoid technology to study tissue regeneration, constructing in vitro organoid models to develop regenerative strategies for injury repair and functional restoration.",
      "tags_zh": "类器官,再生,组织修复,干细胞",
      "tags_en": "Organoid,Regeneration,Tissue Repair,Stem Cells",
      "file": "regenerative-medicine.md",
      "body": ""
    },
    {
      "sort": 4,
      "title_zh": "细胞治疗",
      "title_en": "Cell Therapy",
      "desc_zh": "面向免疫细胞治疗与干细胞治疗的临床转化研究，优化细胞治疗产品制备工艺，推动从实验室到临床的转化。",
      "desc_en": "Translational research on immune cell and stem cell therapy, optimizing manufacturing processes to advance bench-to-bedside translation.",
      "tags_zh": "免疫治疗,基因编辑,转化医学,工艺开发",
      "tags_en": "Immunotherapy,Gene Editing,Translational,Manufacturing",
      "file": "cell-therapy.md",
      "body": ""
    },
    {
      "sort": 5,
      "title_zh": "生殖衰老",
      "title_en": "Reproductive Aging",
      "desc_zh": "聚焦生殖细胞与生殖器官的衰老过程，解析卵母细胞老化与卵巢功能衰退的分子机制，探索延缓生殖衰老的干预策略。",
      "desc_en": "Focusing on germ cell and reproductive organ aging, dissecting molecular mechanisms of oocyte aging and ovarian function decline, exploring intervention strategies to delay reproductive aging.",
      "tags_zh": "卵母细胞,卵巢,表观遗传,线粒体",
      "tags_en": "Oocyte,Ovary,Epigenetics,Mitochondria",
      "file": "reproductive-aging.md",
      "body": ""
    },
    {
      "sort": 6,
      "title_zh": "不孕不育",
      "title_en": "Infertility",
      "desc_zh": "从遗传学、表观遗传学与细胞生物学角度系统研究不孕不育的发病机制，为临床诊断与精准治疗提供生物标志物与干预靶点。",
      "desc_en": "Systematically studying infertility pathogenesis from genetic, epigenetic, and cellular biology perspectives, providing biomarkers and intervention targets for clinical diagnosis and precision treatment.",
      "tags_zh": "配子发生,胚胎阻滞,生物标志物,临床",
      "tags_en": "Gametogenesis,Embryo Arrest,Biomarker,Clinical",
      "file": "infertility.md",
      "body": ""
    }
  ]
};
